import { useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowDownRight, ArrowRight, ArrowSquareOut, ArrowUpRight, BookmarkSimple,
  CaretDown, ChartLineUp, Check, Circle, FunnelSimple, GameController, Info,
  MagnifyingGlass, Star, TrendUp, UsersThree, X,
} from "@phosphor-icons/react";

const games = {
  elden: { id: "elden-ring", slug: "elden-ring", title: "Elden Ring", shortTitle: "Elden Ring", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_hero.jpg", score: 94.7, historicalPopularity: 97, genres: ["RPG", "Ação", "Mundo aberto"], stores: ["steam"], trend: 5, summary: "Explore as Terras Intermédias em uma aventura de fantasia sombria, desafios intensos e liberdade para criar sua própria jornada.", metric: "68 mil jogadores simultâneos" },
  wukong: { id: "black-myth-wukong", slug: "black-myth-wukong", title: "Black Myth: Wukong", shortTitle: "Black Myth: Wukong", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/library_hero.jpg", score: 90.1, historicalPopularity: 93.8, genres: ["RPG", "Ação", "Soulslike"], stores: ["steam", "epic"], trend: 2, summary: "Uma jornada inspirada na mitologia chinesa, com combates precisos, criaturas lendárias e cenários grandiosos.", metric: "42 mil jogadores simultâneos" },
  baldur: { id: "baldurs-gate-3", slug: "baldurs-gate-3", title: "Baldur's Gate 3", shortTitle: "Baldur's Gate 3", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_hero.jpg", score: 88.3, historicalPopularity: 96.4, genres: ["RPG", "Estratégia", "Cooperativo"], stores: ["steam"], trend: -1, summary: "Reúna seu grupo e retorne aos Reinos Esquecidos em um RPG de escolhas profundas e combates estratégicos.", metric: "78 mil jogadores simultâneos" },
  hades: { id: "hades-2", slug: "hades-2", title: "Hades II", shortTitle: "Hades II", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/library_hero.jpg", score: 86.2, historicalPopularity: 89.6, genres: ["Roguelike", "Ação", "Indie"], stores: ["steam", "epic"], trend: 3, summary: "Enfrente forças do tempo em um roguelike de ação veloz, personagens marcantes e progressão constante.", metric: "35 mil jogadores simultâneos" },
  cyberpunk: { id: "cyberpunk-2077", slug: "cyberpunk-2077", title: "Cyberpunk 2077", shortTitle: "Cyberpunk 2077", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_hero.jpg", score: 83.6, historicalPopularity: 95.1, genres: ["RPG", "Ação", "Mundo aberto"], stores: ["steam", "epic"], trend: -2, summary: "Viva como um mercenário em Night City e construa sua lenda em um RPG de ação futurista.", metric: "52 mil jogadores simultâneos" },
  witcher: { id: "the-witcher-3-wild-hunt", slug: "the-witcher-3-wild-hunt", title: "The Witcher 3: Wild Hunt", shortTitle: "The Witcher 3: Wild Hunt", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_hero.jpg", score: 82.8, historicalPopularity: 98.2, genres: ["RPG", "Ação", "Mundo aberto"], stores: ["steam", "epic"], trend: 1, summary: "Cace monstros e atravesse um continente em guerra como Geralt de Rívia.", metric: "32 mil jogadores simultâneos" },
  rdr2: { id: "red-dead-redemption-2", slug: "red-dead-redemption-2", title: "Red Dead Redemption 2", shortTitle: "Red Dead Redemption 2", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_hero.jpg", score: 81.2, historicalPopularity: 96.2, genres: ["Ação", "Aventura", "Mundo aberto"], stores: ["steam", "epic"], trend: 0, summary: "Acompanhe Arthur Morgan em uma história épica sobre honra e sobrevivência no fim do Velho Oeste.", metric: "46 mil jogadores simultâneos" },
  portal: { id: "portal-2", slug: "portal-2", title: "Portal 2", shortTitle: "Portal 2", coverUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/620/library_600x900_2x.jpg", heroUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/620/library_hero.jpg", score: 78.5, historicalPopularity: 95.8, genres: ["Quebra-cabeça", "Aventura", "Cooperativo"], stores: ["steam"], trend: 1, summary: "Resolva quebra-cabeças engenhosos com portais em uma campanha memorável para um ou dois jogadores.", metric: "7 mil jogadores simultâneos" },
};

const fallback = {
  hero: games.elden,
  topFive: [games.elden, games.wukong, games.baldur, games.hades, games.cyberpunk],
  week: [games.elden, games.wukong, games.baldur, games.hades, games.cyberpunk],
  allTime: [games.witcher, games.elden, games.baldur, games.rdr2, games.portal],
  records: [{ title: games.witcher.title, value: games.witcher.historicalPopularity, label: "Maior popularidade histórica", date: "24 de agosto de 2026", coverUrl: games.witcher.coverUrl, game: games.witcher }],
  updatedAt: "2026-08-31T12:00:00.000Z",
  sourceStatus: { steam: "available", epic: "available", igdb: "available" },
};

const formatScore = (score) => typeof score === "number" ? score.toFixed(1).replace(".", ",") : score || "-";
const formatDate = (date) => new Intl.DateTimeFormat("pt-BR", { day: "numeric", month: "long", year: "numeric" }).format(new Date(date));
const storeLabel = (store) => store === "steam" ? "Steam" : store === "epic" ? "Epic Games" : store;
const statusLabel = (status) => ({ wishlist: "Quero jogar", playing: "Jogando", completed: "Concluído" })[status] || status;
const fallbackForSlug = (slug) => Object.values(games).find((game) => game.slug === slug);

function storeKey(value) {
  if (!value) return "";
  if (typeof value === "string") return value.toLowerCase().replace(/\s+/g, "-");
  return storeKey(value.store || value.key || value.name || value.slug || value.label);
}

function normalizeGame(raw = {}, base = {}) {
  const sourceStores = Array.isArray(raw.stores) ? raw.stores : (base.stores || []);
  const storeLinks = { ...(base.storeLinks || {}) };
  sourceStores.forEach((store) => {
    if (store && typeof store === "object" && store.url) storeLinks[storeKey(store)] = store.url;
  });
  const title = raw.title || raw.name || base.title || "Jogo sem título";
  return {
    ...base, ...raw,
    id: raw.id || base.id || raw.slug || title.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    slug: raw.slug || base.slug || raw.id,
    title,
    shortTitle: raw.shortTitle || raw.short_title || title,
    summary: raw.summary || raw.description || base.summary || "",
    coverUrl: raw.coverUrl || raw.cover_url || base.coverUrl || null,
    heroUrl: raw.heroUrl || raw.hero_url || raw.coverUrl || base.heroUrl || null,
    genres: Array.isArray(raw.genres) ? raw.genres.map((genre) => typeof genre === "string" ? genre : genre.name).filter(Boolean) : (base.genres || []),
    stores: sourceStores.map(storeKey).filter(Boolean).length ? sourceStores.map(storeKey).filter(Boolean) : (base.stores || []),
    storeLinks,
  };
}

function normalizeDashboard(payload = {}, current = fallback) {
  const normalizeList = (items, base) => Array.isArray(items) && items.length ? items.map((item) => normalizeGame(item, fallbackForSlug(item.slug) || {})) : base;
  const records = Array.isArray(payload.records) && payload.records.length ? payload.records.map((record) => ({
    ...record,
    game: record.game ? normalizeGame(record.game, fallbackForSlug(record.game.slug) || {}) : current.records[0].game,
    coverUrl: record.coverUrl || record.game?.coverUrl || current.records[0].coverUrl,
    title: record.game?.title || record.title || current.records[0].title,
    date: record.achievedAt ? formatDate(record.achievedAt) : record.date || current.records[0].date,
  })) : current.records;
  return { ...current, ...payload, hero: payload.hero ? normalizeGame(payload.hero, current.hero) : current.hero, topFive: normalizeList(payload.topFive, current.topFive), week: normalizeList(payload.week, current.week), allTime: normalizeList(payload.allTime, current.allTime), records };
}

async function requestJson(url, options = {}) {
  const response = await fetch(url, options);
  const body = response.status === 204 ? null : await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || "Não foi possível concluir a operação.");
  return body;
}

function SafeImage({ src, alt, className = "", ...props }) {
  const [url, setUrl] = useState(src);
  useEffect(() => setUrl(src), [src]);
  return <img className={className} src={url} alt={alt} loading="lazy" onError={() => setUrl("https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80")} {...props} />;
}
function Score({ value, large = false }) { return <span className={large ? "score score-large" : "score"}>{formatScore(value)}</span>; }
function Trend({ value, compact = false }) { if (!value) return <span className="trend neutral">-</span>; const positive = value > 0; return <span className={`trend ${positive ? "positive" : "negative"}`}>{positive ? <ArrowUpRight size={compact ? 15 : 16} weight="bold" /> : <ArrowDownRight size={compact ? 15 : 16} weight="bold" />}{Math.abs(value)}</span>; }

function Header({ view, onNavigate, search, setSearch, compareCount }) {
  return <header className={`site-header ${view === "home" ? "site-header-overlay" : ""}`}>
    <button className="brand" onClick={() => onNavigate("home")} aria-label="SteamTwo, início"><span>Steam</span><b>Two</b></button>
    <nav aria-label="Navegação principal">{[["home", "Início"], ["catalog", "Catálogo"], ["rankings", "Rankings"], ["library", "Minha biblioteca"]].map(([key, label]) => <button key={key} className={view === key ? "active" : ""} onClick={() => onNavigate(key)}>{label}</button>)}</nav>
    <button className="compare-link" onClick={() => onNavigate("compare")} disabled={compareCount < 2} aria-label={`Comparar ${compareCount} jogos`}>Comparar <b>{compareCount}</b></button>
    <label className="search-box"><MagnifyingGlass size={20} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar jogos" aria-label="Buscar jogos" /></label>
  </header>;
}

function LibraryButton({ item, onSave, game, compact = false }) { return <button className={`list-button ${item ? "saved" : ""}`} onClick={() => onSave(game, item?.status || "wishlist", item?.note || "")}><BookmarkSimple size={compact ? 16 : 19} weight={item ? "fill" : "regular"} /> {item ? "Na minha biblioteca" : "Adicionar à biblioteca"}</button>; }
function CompareButton({ active, onToggle }) { return <button className={`compare-button ${active ? "selected" : ""}`} onClick={onToggle} aria-pressed={active}>{active ? "Selecionado" : "Comparar"}</button>; }

function Hero({ game, onDetails, onMethodology, libraryItem, onSave }) {
  return <section className="hero" style={{ "--hero-image": `url(${game.heroUrl})` }}><div className="hero-content"><div className="spotlight"><span>DESTAQUE DO CATÁLOGO</span><Circle size={7} weight="fill" color="var(--blue)" /><time>{formatDate("2026-08-31")}</time></div><div className="eyebrow">O JOGO DO MOMENTO</div><h1>{game.title}</h1><p>{game.summary}</p><div className="hero-actions"><button className="primary-button" onClick={onDetails}>Ver detalhes <ArrowRight size={18} /></button><LibraryButton game={game} item={libraryItem} onSave={onSave} /></div></div><aside className="hero-score"><div className="score-heading"><h2>Índice SteamTwo</h2><button onClick={onMethodology}>Como calculamos <Info size={15} /></button></div><div><Score value={game.score} large /> <span className="out-of">/100</span></div><p>Ranking combinado de Steam e Epic Games, criado a partir de dados públicos de popularidade e engajamento.</p><div className="score-lines"><span><TrendUp size={19} /> Tração recente <b>{Math.min(99, Math.round(game.score + 1))}</b></span><span><Star size={19} /> Popularidade <b>{Math.round(game.historicalPopularity || game.score)}</b></span><span><UsersThree size={19} /> Em alta <b>{game.trend > 0 ? "+" : ""}{game.trend || 0}</b></span></div><small>Atualizado em {formatDate("2026-08-31")}</small></aside></section>;
}
function TopStrip({ items, onDetails }) { return <section className="top-strip" aria-label="Top cinco da semana">{items.map((game, index) => <button className="top-item" key={game.id} onClick={() => onDetails(game)}><strong>{index + 1}</strong><SafeImage src={game.coverUrl} alt="" /><span><b>{game.shortTitle}</b><Score value={game.score} /><Trend value={game.trend} compact /></span></button>)}</section>; }
function StoreFilters({ value, onChange }) { return <div className="store-filter" role="tablist" aria-label="Filtrar por loja">{[["all", "Todos"], ["steam", "Steam"], ["epic", "Epic Games"]].map(([key, label]) => <button key={key} className={value === key ? "selected" : ""} onClick={() => onChange(key)} role="tab" aria-selected={value === key}>{label}</button>)}</div>; }
function WeekList({ items, onDetails }) { return <div className="week-list">{items.map((game, index) => <button className="week-row" key={game.id} onClick={() => onDetails(game)}><strong>{index + 1}</strong><SafeImage src={game.coverUrl} alt="" /><span className="week-title">{game.shortTitle}</span><Score value={game.score} /><Trend value={game.trend} /></button>)}</div>; }
function AllTime({ items, onDetails }) { return <div className="poster-grid">{items.slice(0, 5).map((game) => <button className="poster" key={game.id} onClick={() => onDetails(game)}><SafeImage src={game.coverUrl} alt={`Capa de ${game.shortTitle}`} /><span className="poster-score">{formatScore(game.score)}</span></button>)}</div>; }
function RecordCard({ record, onDetails }) { return <button className="record-card" onClick={() => onDetails(record.game)}><div className="section-kicker">RECORDE MONITORADO</div><p>{record.label}</p><Score value={record.value} /><SafeImage src={record.coverUrl} alt="" /><b>{record.title}</b><small>Atualizado em<br />{record.date}</small></button>; }

function Home({ data, onDetails, onMethodology, libraryBySlug, onSave }) {
  const [store, setStore] = useState("all");
  const week = useMemo(() => store === "all" ? data.week : data.week.filter((game) => game.stores.includes(store)), [data.week, store]);
  return <><Hero game={data.hero} onDetails={() => onDetails(data.hero)} onMethodology={onMethodology} libraryItem={libraryBySlug.get(data.hero.slug)} onSave={onSave} /><TopStrip items={data.topFive} onDetails={onDetails} /><section className="dashboard-grid"><div className="week-panel"><div className="section-head"><div><h2>ÚLTIMA SEMANA</h2><p>Ranking de popularidade atual</p></div><StoreFilters value={store} onChange={setStore} /></div><WeekList items={week} onDetails={onDetails} /><button className="more-link" onClick={() => onDetails(null)}>Ver ranking completo <ArrowRight size={19} /></button></div><div className="alltime-panel"><div className="section-head"><div><h2>DE SEMPRE</h2><p>Jogos com maior relevância histórica no catálogo.</p></div></div><AllTime items={data.allTime} onDetails={onDetails} /><button className="more-link" onClick={() => onDetails(null)}>Explorar rankings <ArrowRight size={19} /></button></div><RecordCard record={data.records[0]} onDetails={onDetails} /></section></>;
}

function GameCard({ game, onDetails, libraryItem, onSave, compareActive, onCompare }) { return <article className="game-card"><button className="game-card-main" onClick={() => onDetails(game)} aria-label={`Abrir ${game.shortTitle}`}><SafeImage src={game.coverUrl} alt={`Capa de ${game.shortTitle}`} /><div><span className="game-card-score"><Score value={game.score} /></span><h3>{game.shortTitle}</h3><p>{game.genres.join(" · ")}</p><span className="card-stores">{game.stores.map(storeLabel).join(" · ")}</span></div></button><div className="card-actions"><LibraryButton game={game} item={libraryItem} onSave={onSave} compact /><CompareButton active={compareActive} onToggle={() => onCompare(game)} /></div></article>; }

function Catalog({ data, query, onDetails, libraryBySlug, onSave, compareSlugs, onCompare }) {
  const [store, setStore] = useState("all"); const [genre, setGenre] = useState("all"); const [apiGames, setApiGames] = useState(null); const [loading, setLoading] = useState(true); const [apiError, setApiError] = useState(false);
  const fallbackGames = useMemo(() => [...data.topFive, ...data.allTime].filter((game, index, list) => list.findIndex((item) => item.id === game.id) === index), [data]);
  useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams(); if (query) params.set("q", query); if (store !== "all") params.set("store", store); if (genre !== "all") params.set("genre", genre); setLoading(true); setApiError(false); requestJson(`/api/games?${params}`, { signal: controller.signal }).then((payload) => setApiGames((payload.items || []).map((item) => normalizeGame(item, fallbackForSlug(item.slug) || {})))).catch((error) => { if (error.name !== "AbortError") { setApiError(true); setApiGames(null); } }).finally(() => setLoading(false)); return () => controller.abort(); }, [query, store, genre]);
  const source = apiGames ?? fallbackGames; const genres = [...new Set(source.flatMap((game) => game.genres || []))].sort((a, b) => a.localeCompare(b, "pt-BR")); const filtered = source.filter((game) => (!query || game.title.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))) && (store === "all" || game.stores.includes(store)) && (genre === "all" || game.genres.includes(genre)));
  return <section className="catalog-page"><div className="page-intro"><div><span className="eyebrow">BIBLIOTECA STEAMTWO</span><h1>Catálogo de jogos</h1><p>Salve títulos na sua biblioteca pessoal ou escolha até três para comparar.</p></div><GameController size={58} weight="thin" /></div><div className="catalog-toolbar"><div className="filter-control"><FunnelSimple size={18} /><StoreFilters value={store} onChange={setStore} /></div><label className="select-control">Gênero <select value={genre} onChange={(event) => setGenre(event.target.value)}><option value="all">Todos os gêneros</option>{genres.map((item) => <option value={item} key={item}>{item}</option>)}</select><CaretDown size={16} /></label></div>{loading ? <div className="empty-state"><GameController size={34} /><h2>Carregando catálogo</h2><p>Buscando jogos na API do SteamTwo...</p></div> : filtered.length ? <div className="catalog-grid">{filtered.map((game) => <GameCard key={game.id} game={game} onDetails={onDetails} libraryItem={libraryBySlug.get(game.slug)} onSave={onSave} compareActive={compareSlugs.includes(game.slug)} onCompare={onCompare} />)}</div> : <div className="empty-state"><GameController size={34} /><h2>{apiError ? "Catálogo temporariamente indisponível" : "Nenhum jogo encontrado"}</h2><p>{apiError ? "A interface continua disponível com os últimos dados válidos." : "Tente outra busca ou remova algum filtro."}</p></div>}</section>;
}

function Rankings({ data, onDetails }) { return <section className="rankings-page"><div className="page-intro"><div><span className="eyebrow">RANKINGS</span><h1>Quem está no topo?</h1><p>Veja como os jogos evoluíram nos rankings monitorados pelo SteamTwo.</p></div><ChartLineUp size={58} weight="thin" /></div><div className="ranking-table"><div className="table-head"><span>#</span><span>Jogo</span><span>Índice SteamTwo</span><span>Variação</span></div>{data.topFive.map((game, index) => <button className="table-row" key={game.id} onClick={() => onDetails(game)}><strong>{index + 1}</strong><span><SafeImage src={game.coverUrl} alt="" /><b>{game.shortTitle}</b></span><Score value={game.score} /><Trend value={game.trend} /></button>)}</div></section>; }

function Detail({ game, onBack, onMethodology, libraryItem, onSave, compareActive, onCompare }) { const storeUrl = game.storeLinks?.[game.stores?.[0]] || (game.stores?.[0] === "epic" ? `https://store.epicgames.com/en-US/browse?q=${encodeURIComponent(game.title)}` : `https://store.steampowered.com/search/?term=${encodeURIComponent(game.title)}`); return <section className="detail-page"><button className="back-link" onClick={onBack}><ArrowRight size={17} /> Voltar</button><div className="detail-hero" style={{ "--detail-image": `url(${game.heroUrl})` }}><div><span className="eyebrow">DETALHE DO JOGO</span><h1>{game.shortTitle}</h1><div className="detail-tags">{game.genres.map((genre) => <span key={genre}>{genre}</span>)}</div><p>{game.summary}</p><div className="detail-actions"><a className="primary-button" href={storeUrl} target="_blank" rel="noreferrer">Abrir na loja <ArrowSquareOut size={17} /></a><LibraryButton game={game} item={libraryItem} onSave={onSave} /><CompareButton active={compareActive} onToggle={() => onCompare(game)} /></div></div><div className="detail-score"><span>ÍNDICE STEAMTWO</span><Score value={game.score} large /><small>/ 100</small><button onClick={onMethodology}>Como calculamos <Info size={14} /></button></div></div><div className="detail-columns"><article><h2>Sobre este jogo</h2><p>{game.summary} O índice combina sinais públicos para oferecer uma leitura comparável entre os títulos acompanhados.</p></article><aside><h2>Fontes acompanhadas</h2><div className="source-pills">{game.stores.map((store) => <span key={store}><Check size={14} /> {storeLabel(store)}</span>)}<span><Check size={14} /> IGDB</span></div><small>Última atualização: {formatDate("2026-08-31")}</small></aside></div></section>; }

function Library({ items, loading, onSave, onRemove, onDetails }) {
  const [status, setStatus] = useState("all"); const visible = status === "all" ? items : items.filter((item) => item.status === status);
  return <section className="library-page"><div className="page-intro"><div><span className="eyebrow">MINHA BIBLIOTECA</span><h1>Seu próximo jogo</h1><p>Uma lista pessoal persistida no PostgreSQL quando o banco está configurado.</p></div><BookmarkSimple size={58} weight="thin" /></div><div className="library-toolbar"><div className="library-status-buttons" role="group" aria-label="Status da biblioteca">{[["all", "Todos"], ["wishlist", "Quero jogar"], ["playing", "Jogando"], ["completed", "Concluído"]].map(([key, label]) => <button key={key} className={status === key ? "selected" : ""} onClick={() => setStatus(key)}>{label}</button>)}</div></div>{loading ? <div className="empty-state"><BookmarkSimple size={34} /><h2>Carregando a biblioteca</h2></div> : visible.length ? <div className="library-grid">{visible.map((item) => <LibraryCard key={item.game.slug} item={item} onSave={onSave} onRemove={onRemove} onDetails={onDetails} />)}</div> : <div className="empty-state"><BookmarkSimple size={34} /><h2>Sua biblioteca está vazia</h2><p>Adicione jogos pelo catálogo e mantenha uma nota sobre o que quer jogar.</p></div>}</section>;
}
function LibraryCard({ item, onSave, onRemove, onDetails }) { const [note, setNote] = useState(item.note || ""); useEffect(() => setNote(item.note || ""), [item.note]); return <article className="library-card"><SafeImage src={item.game.coverUrl} alt={`Capa de ${item.game.shortTitle || item.game.title}`} /><div className="library-card-content"><div><span className="library-badge">{statusLabel(item.status)}</span><h2>{item.game.shortTitle || item.game.title}</h2><p>{item.game.genres.join(" · ")}</p></div><label>Progresso<select value={item.status} onChange={(event) => onSave(item.game, event.target.value, note)}><option value="wishlist">Quero jogar</option><option value="playing">Jogando</option><option value="completed">Concluído</option></select></label><label>Minha nota<textarea value={note} maxLength="280" onChange={(event) => setNote(event.target.value)} onBlur={() => note !== (item.note || "") && onSave(item.game, item.status, note)} placeholder="Ex.: jogar com amigos no fim de semana" /></label><div className="library-card-actions"><button className="more-link" onClick={() => onDetails(item.game)}>Ver detalhes <ArrowRight size={17} /></button><button className="remove-button" onClick={() => onRemove(item.game.slug)}>Remover</button></div></div></article>; }

function Compare({ selected, onDetails, onRemove }) {
  const [result, setResult] = useState(null); const [error, setError] = useState(""); const slugs = selected.map((game) => game.slug);
  useEffect(() => { const controller = new AbortController(); if (slugs.length < 2) { setResult(null); return () => controller.abort(); } setError(""); requestJson(`/api/compare?slugs=${encodeURIComponent(slugs.join(","))}`, { signal: controller.signal }).then((payload) => setResult(payload)).catch((requestError) => { if (requestError.name !== "AbortError") setError(requestError.message); }); return () => controller.abort(); }, [slugs.join(",")]);
  const gamesToShow = result?.items?.map((game) => normalizeGame(game, fallbackForSlug(game.slug) || {})) || selected;
  return <section className="compare-page"><div className="page-intro"><div><span className="eyebrow">COMPARADOR</span><h1>Compare lado a lado</h1><p>Escolha dois ou três jogos no catálogo para revisar os dados mais importantes.</p></div><ChartLineUp size={58} weight="thin" /></div>{selected.length < 2 ? <div className="empty-state"><ChartLineUp size={34} /><h2>Escolha pelo menos dois jogos</h2><p>Use o botão “Comparar” no catálogo ou na tela de detalhes.</p></div> : <><div className="comparison-summary"><span><b>{result?.summary?.scoreDifference?.toFixed?.(1)?.replace(".", ",") || "-"}</b> pontos de diferença no índice</span><span>Gêneros em comum: <b>{result?.summary?.sharedGenres?.join(", ") || "Nenhum"}</b></span></div>{error && <p className="api-note" role="status">A comparação está usando os dados disponíveis na interface.</p>}<div className="comparison-grid">{gamesToShow.map((game) => <article className="comparison-card" key={game.slug}><button className="comparison-remove" onClick={() => onRemove(game)} aria-label={`Remover ${game.shortTitle} da comparação`}><X size={16} /></button><SafeImage src={game.coverUrl} alt={`Capa de ${game.shortTitle}`} /><h2>{game.shortTitle}</h2><Score value={game.score} large /><small>Índice SteamTwo</small><dl><div><dt>Popularidade histórica</dt><dd>{formatScore(game.historicalPopularity)}</dd></div><div><dt>Variação</dt><dd><Trend value={game.trend} /></dd></div><div><dt>Lojas</dt><dd>{game.stores.map(storeLabel).join(" · ")}</dd></div><div><dt>Gêneros</dt><dd>{game.genres.join(" · ")}</dd></div></dl><button className="more-link" onClick={() => onDetails(game)}>Ver detalhes <ArrowRight size={17} /></button></article>)}</div></>}</section>;
}

function Methodology({ onClose }) { const closeRef = useRef(null); const previousFocus = useRef(null); useEffect(() => { previousFocus.current = document.activeElement; closeRef.current?.focus(); const closeOnEscape = (event) => event.key === "Escape" && onClose(); document.addEventListener("keydown", closeOnEscape); return () => { document.removeEventListener("keydown", closeOnEscape); previousFocus.current?.focus?.(); }; }, [onClose]); return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="methodology-modal" role="dialog" aria-modal="true" aria-labelledby="method-title"><button ref={closeRef} className="modal-close" aria-label="Fechar" onClick={onClose}><X size={20} /></button><span className="eyebrow">TRANSPARÊNCIA</span><h2 id="method-title">Como calculamos</h2><p>O Índice SteamTwo combina sinais públicos de popularidade para destacar jogos em alta, sem representar número de vendas ou propriedade dos títulos.</p><div className="method-grid"><div><strong>01</strong><h3>Tração recente</h3><p>Posições Steam e Epic são normalizadas pelos rankings mais recentes disponíveis.</p></div><div><strong>02</strong><h3>Popularidade</h3><p>O histórico usa a popularidade pública consultada na IGDB.</p></div><div><strong>03</strong><h3>Limitações</h3><p>A Epic não divulga contagem pública de jogadores. Fontes indisponíveis são sinalizadas.</p></div></div><small className="method-foot">Fontes: Steam, Epic Games e IGDB.</small></section></div>; }

export function App() {
  const [data, setData] = useState(fallback); const [loading, setLoading] = useState(true); const [stale, setStale] = useState(false); const [search, setSearch] = useState(""); const [view, setView] = useState("home"); const [selected, setSelected] = useState(null); const [methodology, setMethodology] = useState(false); const [library, setLibrary] = useState([]); const [libraryLoading, setLibraryLoading] = useState(true); const [compare, setCompare] = useState([]); const [notice, setNotice] = useState("");
  const libraryBySlug = useMemo(() => new Map(library.map((item) => [item.game.slug, item])), [library]);
  const updateLibrary = (item) => setLibrary((current) => [item, ...current.filter((currentItem) => currentItem.game.slug !== item.game.slug)]);
  const saveLibrary = async (game, status = "wishlist", note = "") => { try { const item = await requestJson(`/api/library/${encodeURIComponent(game.slug)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, note }) }); updateLibrary({ ...item, game: normalizeGame(item.game, fallbackForSlug(item.game.slug) || game) }); setNotice(`${game.shortTitle || game.title} foi salvo na sua biblioteca.`); } catch (error) { setNotice(error.message); } };
  const removeLibrary = async (slug) => { try { await requestJson(`/api/library/${encodeURIComponent(slug)}`, { method: "DELETE" }); setLibrary((items) => items.filter((item) => item.game.slug !== slug)); setNotice("Jogo removido da biblioteca."); } catch (error) { setNotice(error.message); } };
  const toggleCompare = (game) => setCompare((current) => current.some((item) => item.slug === game.slug) ? current.filter((item) => item.slug !== game.slug) : current.length >= 3 ? current : [...current, game]);
  const loadDetail = (slug, base) => { setLoading(true); requestJson(`/api/games/${encodeURIComponent(slug)}`).then((payload) => { const raw = payload.game || payload.data || payload; setSelected(normalizeGame(raw, base)); setStale(false); }).catch(() => setStale(true)).finally(() => setLoading(false)); };
  useEffect(() => { const applyLocation = () => { const path = window.location.pathname; const nextView = path.startsWith("/catalogo") ? "catalog" : path.startsWith("/rankings") ? "rankings" : path.startsWith("/minha-biblioteca") ? "library" : path.startsWith("/comparar") ? "compare" : "home"; if (path.startsWith("/jogos/")) { const slug = decodeURIComponent(path.slice("/jogos/".length)); const base = fallbackForSlug(slug) || normalizeGame({ slug, title: slug.replace(/-/g, " ") }); setSelected(base); setView("home"); loadDetail(slug, base); } else { setSelected(null); setView(nextView); } window.scrollTo({ top: 0, behavior: "smooth" }); }; applyLocation(); window.addEventListener("popstate", applyLocation); return () => window.removeEventListener("popstate", applyLocation); }, []);
  useEffect(() => { const controller = new AbortController(); requestJson("/api/dashboard", { signal: controller.signal }).then((payload) => { setData((current) => normalizeDashboard(payload, current)); setStale(false); }).catch((error) => { if (error.name !== "AbortError") setStale(true); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  useEffect(() => { const controller = new AbortController(); requestJson("/api/library", { signal: controller.signal }).then((payload) => setLibrary((payload.items || []).map((item) => ({ ...item, game: normalizeGame(item.game, fallbackForSlug(item.game.slug) || {}) })))).catch(() => setNotice("A biblioteca será salva quando a API estiver disponível.")).finally(() => setLibraryLoading(false)); return () => controller.abort(); }, []);
  useEffect(() => { if (!notice) return undefined; const timeout = window.setTimeout(() => setNotice(""), 3600); return () => window.clearTimeout(timeout); }, [notice]);
  const navigate = (next) => { setSelected(null); setView(next); const paths = { home: "/", catalog: "/catalogo", rankings: "/rankings", library: "/minha-biblioteca", compare: "/comparar" }; window.history.pushState({}, "", paths[next]); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const details = (game) => { if (!game) return navigate("rankings"); const normalized = normalizeGame(game, fallbackForSlug(game.slug) || {}); setSelected(normalized); window.history.pushState({}, "", `/jogos/${normalized.slug}`); window.scrollTo({ top: 0, behavior: "smooth" }); loadDetail(normalized.slug, normalized); };
  const shownView = selected ? "detail" : view;
  return <div className="app-shell"><Header view={shownView} onNavigate={navigate} search={search} setSearch={setSearch} compareCount={compare.length} />{loading && <div className="loading-bar" aria-label="Carregando dados" />}<p className="sr-only" aria-live="polite">{notice}</p><main>{selected ? <Detail game={selected} onBack={() => navigate("home")} onMethodology={() => setMethodology(true)} libraryItem={libraryBySlug.get(selected.slug)} onSave={saveLibrary} compareActive={compare.some((game) => game.slug === selected.slug)} onCompare={toggleCompare} /> : view === "catalog" ? <Catalog data={data} query={search} onDetails={details} libraryBySlug={libraryBySlug} onSave={saveLibrary} compareSlugs={compare.map((game) => game.slug)} onCompare={toggleCompare} /> : view === "rankings" ? <Rankings data={data} onDetails={details} /> : view === "library" ? <Library items={library} loading={libraryLoading} onSave={saveLibrary} onRemove={removeLibrary} onDetails={details} /> : view === "compare" ? <Compare selected={compare} onDetails={details} onRemove={toggleCompare} /> : <Home data={data} onDetails={details} onMethodology={() => setMethodology(true)} libraryBySlug={libraryBySlug} onSave={saveLibrary} />}</main><footer><span>SteamTwo</span><span>Dados públicos, rankings transparentes.</span><button onClick={() => setMethodology(true)}>Metodologia</button>{stale && <small>Últimos dados válidos · {formatDate(data.updatedAt)}</small>}</footer>{methodology && <Methodology onClose={() => setMethodology(false)} />}</div>;
}
